#!/usr/bin/env python3
# coding: utf-8
"""Romanesco as a parametric L-system, rendered with POV-Ray.

    axiom : Apex(1)
    p1    : Apex(s) : s >= s_min -> [ ^(tilt) F(stalk*s) Apex(s*r_lat) ] F(dz*s) /(phi) Apex(s*r_main)
    p2    : Apex(s) : s <  s_min -> f(s/2) B(s)

Turtle symbols (ABOP convention):
    F(d) move forward d and draw a stem    f(d) move forward d without drawing
    /(a) roll around the heading            \\(a) roll the other way
    ^(a) pitch up                           &(a) pitch down
    +(a) turn left                          -(a) turn right
    [ ]  push / pop the turtle state        B(s) bud (sphere) of size s

The divergence angle phi must be a roll *outside* the brackets so that it
accumulates along the main axis; otherwise every lateral points the same way.
With dz = 1 - r_main the main axis generated by Apex(s) is exactly s long.
Without the stalk the laterals start on the axis line, so they must be large
(r_lat ~ 0.6, tilt ~ 50) to reach the surface and most of each floret is buried;
the stalk plays the role of the thick core so that florets emerge from the
conical surface (try --stalk 0 --r-lateral 0.63 --tilt 48 --min-size 0.03).

Usage:
    make                                         # -> lsystem.png
    make clean all ARGS='--elevation 75' SIZE=800
    python3 romanesco-lsystem.py --derive 2      # show the rewritten strings
"""

import argparse
import sys
from math import radians, degrees, cos, sin, atan, sqrt


def parse_args():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--divergence', type=float, default=137.5, help='phi [deg]')
    p.add_argument('--tilt', type=float, default=50.0, help='lateral pitch [deg]')
    p.add_argument('--r-main', type=float, default=0.965)
    p.add_argument('--r-lateral', type=float, default=0.38)
    p.add_argument('--stalk', type=float, default=0.35,
                   help='lateral stalk length relative to s (0: no stalk)')
    p.add_argument('--dz', type=float, default=None,
                   help='internode length relative to s (default: 1 - r_main)')
    p.add_argument('--min-size', type=float, default=0.008,
                   help='s_min; smaller means more detail (and many more buds)')
    p.add_argument('--bud', type=float, default=0.55, help='bud radius / s')
    p.add_argument('--stems', action='store_true', help='also draw F as cylinders')
    p.add_argument('--stem-radius', type=float, default=0.004)
    p.add_argument('--elevation', type=float, default=35.0, help='camera [deg]')
    p.add_argument('--azimuth', type=float, default=0.0, help='camera [deg]')
    p.add_argument('--derive', type=int, metavar='N',
                   help='print the first N derivation steps and exit')
    args = p.parse_args()
    if args.dz is None:
        args.dz = 1.0 - args.r_main
    return args


# ---------------------------------------------------------------- L-system

def produce(module, P):
    """Successor of a module, or None if the module is terminal."""
    if module[0] != 'Apex':
        return None
    s = module[1]
    if s < P.min_size:
        return [('f', s * 0.5), ('B', s)]
    lateral = [('[',), ('^', P.tilt)]
    if P.stalk > 0:
        lateral.append(('F', P.stalk * s))
    lateral += [('Apex', s * P.r_lateral), (']',)]
    return lateral + [('F', P.dz * s), ('/', P.divergence), ('Apex', s * P.r_main)]


def derive(axiom, n, P):
    word = list(axiom)
    for _ in range(n):
        new = []
        for m in word:
            succ = produce(m, P)
            new.extend(succ if succ is not None else [m])
        word = new
        yield word


def fmt(word):
    return ' '.join(m[0] if len(m) == 1 else '{}({:.4g})'.format(*m) for m in word)


# ------------------------------------------------------------------ turtle

def add(a, b):
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def mul(a, k):
    return (a[0] * k, a[1] * k, a[2] * k)


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1],
            a[2] * b[0] - a[0] * b[2],
            a[0] * b[1] - a[1] * b[0])


def rotate(v, axis, deg):
    """Rotate v (perpendicular to the unit vector axis) around axis."""
    t = radians(deg)
    return add(mul(v, cos(t)), mul(cross(axis, v), sin(t)))


class Turtle:
    def __init__(self):
        self.pos = (0.0, 0.0, 0.0)
        self.H = (0.0, 1.0, 0.0)   # heading (POV-Ray y is up)
        self.L = (1.0, 0.0, 0.0)
        self.U = (0.0, 0.0, 1.0)
        self.stack = []
        self.buds = []
        self.stems = []

    def apply(self, m):
        sym = m[0]
        if sym in ('F', 'f'):
            end = add(self.pos, mul(self.H, m[1]))
            if sym == 'F':
                self.stems.append((self.pos, end))
            self.pos = end
        elif sym in ('/', '\\'):
            a = m[1] if sym == '/' else -m[1]
            self.L, self.U = rotate(self.L, self.H, a), rotate(self.U, self.H, a)
        elif sym in ('^', '&'):
            a = m[1] if sym == '^' else -m[1]
            self.H, self.U = rotate(self.H, self.L, a), rotate(self.U, self.L, a)
        elif sym in ('+', '-'):
            a = m[1] if sym == '+' else -m[1]
            self.H, self.L = rotate(self.H, self.U, a), rotate(self.L, self.U, a)
        elif sym == '[':
            self.stack.append((self.pos, self.H, self.L, self.U))
        elif sym == ']':
            self.pos, self.H, self.L, self.U = self.stack.pop()
        elif sym == 'B':
            self.buds.append((self.pos, m[1]))


def run(word, P, turtle):
    """Rewrite until no production applies, interpreting depth-first.

    Equivalent to deriving the fixed point in parallel and then interpreting
    it, without holding the whole (huge) word in memory.
    """
    for m in word:
        succ = produce(m, P)
        if succ is None:
            turtle.apply(m)
        else:
            run(succ, P, turtle)


# ----------------------------------------------------------------- POV-Ray

def v3(p):
    return '<{:.5f},{:.5f},{:.5f}>'.format(*p)


def write_pov(turtle, P, out):
    rad = [s * P.bud for _, s in turtle.buds]
    lo = [min(p[i] - r for (p, _), r in zip(turtle.buds, rad)) for i in range(3)]
    hi = [max(p[i] + r for (p, _), r in zip(turtle.buds, rad)) for i in range(3)]
    center = tuple((a + b) * 0.5 for a, b in zip(lo, hi))
    R = 0.5 * sqrt(sum((b - a) ** 2 for a, b in zip(lo, hi)))
    dist = 6.0 * R
    el, az = radians(P.elevation), radians(P.azimuth)
    back = (cos(el) * sin(az), sin(el), -cos(el) * cos(az))
    right = (cos(az), 0.0, sin(az))
    up = cross(right, back)
    xs = [sum(a * b for a, b in zip(p, right)) for p, _ in turtle.buds]
    ys = [sum(a * b for a, b in zip(p, up)) for p, _ in turtle.buds]
    cx, cy = (min(xs) + max(xs)) * 0.5, (min(ys) + max(ys)) * 0.5
    c0 = sum(a * b for a, b in zip(center, right)), sum(a * b for a, b in zip(center, up))
    center = add(center, add(mul(right, cx - c0[0]), mul(up, cy - c0[1])))
    half = 0.55 * max(max(xs) - min(xs), max(ys) - min(ys))
    eye = add(center, mul(back, dist))
    fov = degrees(2.0 * atan(half / dist))

    out.write("""// generated by romanesco-lsystem.py
// divergence={0.divergence} tilt={0.tilt} r_main={0.r_main} r_lateral={0.r_lateral} dz={0.dz:.4g} s_min={0.min_size}
// buds={1}
global_settings {{ assumed_gamma 1.0 max_trace_level 20 }}
background {{ rgb 1 }}
camera {{ location {2} look_at {3} angle {4:.4f} right x*image_width/image_height }}
light_source {{ {5} rgb 1.0 }}
light_source {{ {6} rgb 0.35 shadowless }}
light_source {{ {7} rgb 0.25 shadowless }}
#declare tRom = texture {{ pigment {{ rgb <0.55, 0.85, 0.25> }}
                          finish {{ diffuse 0.85 ambient 0.06 specular 0.25 roughness 0.03 }} }}
#declare tStem = texture {{ pigment {{ rgb <0.85, 0.9, 0.7> }} finish {{ diffuse 0.9 }} }}
""".format(P, len(turtle.buds), v3(eye), v3(center), fov,
           v3(add(center, (-3 * dist, 4 * dist, -2 * dist))),
           v3(add(center, (3 * dist, 1 * dist, -3 * dist))),
           v3(add(center, (0, -2 * dist, -1 * dist)))))

    for (p, _), r in zip(turtle.buds, rad):
        out.write('sphere{{{},{:.5f} texture{{tRom}}}}\n'.format(v3(p), r))
    if P.stems:
        for a, b in turtle.stems:
            out.write('cylinder{{{},{},{} texture{{tStem}}}}\n'.format(
                v3(a), v3(b), P.stem_radius))


def main():
    P = parse_args()
    axiom = [('Apex', 1.0)]
    if P.derive is not None:
        print('0: ' + fmt(axiom))
        for i, word in enumerate(derive(axiom, P.derive, P), 1):
            print('{}: {}'.format(i, fmt(word)))
        return
    sys.setrecursionlimit(100000)
    turtle = Turtle()
    run(axiom, P, turtle)
    print('buds: {}, stems: {}'.format(len(turtle.buds), len(turtle.stems)),
          file=sys.stderr)
    write_pov(turtle, P, sys.stdout)


if __name__ == '__main__':
    main()
